#---
#spring:
#  application:
#    name: @pom.artifactId@
#  #在用jar包方式启动的时候，可以通过 --spring.profiles.active=peer1参数指定用的是profiles为peer1的配置文件
#  profiles: peer1
#server:
#  port: 8000
#eureka:
#  instance:
#    #设置注册到eureka服务里的hostname，这个需要在DNS中可以找到或者通过配置/etc/hosts文件来实现
#    hostname: peer1
#  client:
#    serviceUrl:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: @pom.artifactId@
#  profiles: peer2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
#---
#spring:
#  application:
#    name: @pom.artifactId@
#  profiles: peer3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: peer3
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/